services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5673:5672"   # AMQP (5673 instead of default 5672 to avoid conflicts with the possible local RabbitMQ default installation)
      - "15673:15672" # Management UI http://localhost:15673 (default is 15672)
    environment:
      RABBITMQ_DEFAULT_USER: forwarder
      RABBITMQ_DEFAULT_PASS: forwarder

  forwarder:
    build:
      context: .
      dockerfile: Projects/RmqToRestApiForwarder/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Docker
    depends_on:
      - rabbitmq